# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - EmployeeCrudApi/**
      - EmployeeCrudAngular/**

pool:
  vmImage: 'windows-latest'

jobs:
  - job: BuildBackend
    displayName: 'Build Backend'
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.0.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - task: DotNetCoreCLI@2
        displayName: 'Restore Backend Dependencies'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Build Backend'
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration Release'

      - task: DotNetCoreCLI@2
        displayName: 'Run API Tests'
        inputs:
          command: 'test'
          projects: '**/*.Tests.csproj'
          arguments: '--collect:"XPlat Code Coverage"'

      - task: PublishCodeCoverageResults@2
        displayName: 'Publish Backend Code Coverage Results'
        inputs:
          summaryFileLocation: '$(Agent.TempDirectory)/**/*.cobertura.xml'
          failIfCoverageEmpty: false

      - task: DotNetCoreCLI@2
        displayName: 'Publish Backend'
        inputs:
          command: 'publish'
          projects: '**/*.csproj'
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/backend'
    
      - publish: $(Build.ArtifactStagingDirectory)/backend
        artifact: backend

  - job: BuildFrontend
    displayName: 'Build Frontend'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
          checkLatest: true

      - script: |
          cd EmployeeCrudAngular
          npm install
          npm run build --prod
        displayName: 'Install Dependencies and Build Frontend'

      # Comprobar si el directorio dist existe
      - script: |
          if exist EmployeeCrudAngular\dist (
            echo "Dist directory found!"
            dir EmployeeCrudAngular\dist
          ) else (
            echo "Dist directory not found!"
            exit /b 1
          )
        displayName: 'Verify dist Directory Exists'

      # Publicar el artefacto del frontend
      - publish: 'EmployeeCrudAngular/dist/EmployeeCrudAngular'
        artifact: frontend
